Repository gristlabs/grist-core, pull requests merged in 2024-05, with the labels that each got.

#915 Introduce APP_HOME_INTERNAL_URL and fix duplicate docs
  README.md
  app/common/UserAPI.ts
  app/common/gristUrls.ts
  app/gen-server/lib/DocApiForwarder.ts
  app/server/lib/AppEndpoint.ts
  app/server/lib/Authorizer.ts
  app/server/lib/BootProbes.ts
  app/server/lib/DocApi.ts
  app/server/lib/DocWorkerUtils.ts
  app/server/lib/FlexServer.ts
  app/server/lib/GristServer.ts
  app/server/lib/ITestingHooks-ti.ts
  app/server/lib/ITestingHooks.ts
  app/server/lib/TestingHooks.ts
  app/server/lib/requestUtils.ts
  app/server/lib/uploads.ts
  test/server/lib/DocApi.ts
  test/server/lib/helpers/TestProxyServer.ts
  test/server/lib/helpers/TestServer.ts
Labels: anct, preview

#981 Displays the current authentication mechanism in the admin panel
  app/client/ui/AdminPanel.ts
  app/client/ui/AdminPanelCss.ts
  app/common/BootProbe.ts
  app/server/lib/BootProbes.ts
  app/server/lib/FlexServer.ts
  app/server/lib/GristServer.ts
Labels: preview

#946 feat: add translation of vue types when added
  app/client/models/entities/ViewSectionRec.ts
  app/client/ui/PageWidgetPicker.ts
  app/client/ui/RightPanel.ts
  app/client/ui/widgetTypesMap.ts
  static/locales/en.client.json
Labels: anct

#963 reconcile boot and admin pages further
  app/client/boot.ts
  app/client/models/AdminChecks.ts
  app/client/models/AppModel.ts
  app/client/ui/AdminPanel.ts
  app/common/BaseAPI.ts
  app/common/BootProbe.ts
  app/common/InstallAPI.ts
  app/server/lib/Authorizer.ts
  app/server/lib/BootProbes.ts
  app/server/lib/FlexServer.ts
  app/server/lib/GristServer.ts
  app/server/lib/ICreate.ts
  app/server/lib/InstallAdmin.ts
  buildtools/webpack.config.js
  package.json
  sandbox/watch.sh
  static/boot.html
  test/nbrowser/AdminPanel.ts
  test/nbrowser/Boot.ts
Labels: preview

#1004 feat: add new translations
  app/client/ui/AppHeader.ts
  static/locales/en.client.json
Labels: anct
