Repository gristlabs/grist-core, pull requests merged in 2025-09, with the labels that each got.

#1524 fix: Missing translations in Admin panel
  app/client/models/AdminChecks.ts
  app/client/ui/AdminPanel.ts
  app/client/ui/ToggleEnterpriseWidget.ts
  static/locales/en.client.json
Labels: translation, gouv.fr

#1822 Fix translation in ChoiceListEntry: "+{{count}} more"
  static/locales/en.client.json
Labels: gouv.fr

#1772 Explicit coding rules
  documentation/develop.md
Labels: documentation, enhancement

#1837 add a placeholder for "Proposed Changes" UI
  app/client/components/ActionLog.ts
  app/client/components/GristDoc.ts
  app/client/models/TimeQuery.ts
  app/client/ui/ProposedChangesPage.ts
  app/client/ui/ShareMenu.ts
  app/client/ui/Tools.ts
  app/common/ActionSummary.ts
  app/common/TabularDiff.ts
  app/common/TimeQuery.ts
  app/common/gristUrls.ts
  app/server/lib/TimeQuery.ts
  sandbox/grist/imports/import_csv.py
  test/nbrowser/ActionLog.ts
  test/nbrowser/ProposedChangesPage.ts
  test/server/lib/ActionSummary.ts
  test/server/lib/TimeQuery.ts
Labels: preview
