Repository gristlabs/grist-core, pull requests merged in 2025-02, with the labels that each got.

#1409 Adds 'snapshot' mode to external attachments
  .github/workflows/main.yml
  app/server/lib/AttachmentStore.ts
  app/server/lib/AttachmentStoreProvider.ts
  app/server/lib/ExternalStorage.ts
  app/server/lib/FlexServer.ts
  app/server/lib/ICreate.ts
  app/server/lib/MinIOExternalStorage.ts
  app/server/lib/configureMinIOExternalStorage.ts
  app/server/lib/coreCreator.ts
  test/server/lib/AttachmentStoreProvider.ts
  test/server/lib/ExternalStorageAttachmentStore.ts
  test/server/lib/HostedStorageManager.ts
Labels: Attachments

#1358 Adds transfers between stores to external attachments
  app/common/UserAPI.ts
  app/plugin/DocApiTypes-ti.ts
  app/plugin/DocApiTypes.ts
  app/server/generateInitialDocSql.ts
  app/server/lib/ActiveDoc.ts
  app/server/lib/AttachmentFileManager.ts
  app/server/lib/AttachmentStore.ts
  app/server/lib/AttachmentStoreProvider.ts
  app/server/lib/DocApi.ts
  app/server/lib/DocStorage.ts
  app/server/lib/ExternalStorage.ts
  app/server/lib/FlexServer.ts
  app/server/lib/ICreate.ts
  app/server/lib/MinIOExternalStorage.ts
  app/server/lib/configureMinIOExternalStorage.ts
  app/server/lib/coreCreator.ts
  app/server/utils/gristify.ts
  test/server/docTools.ts
  test/server/lib/ActiveDoc.ts
  test/server/lib/AttachmentFileManager.ts
  test/server/lib/AttachmentStoreProvider.ts
  test/server/lib/DocApi.ts
  test/server/lib/DocStorage.js
  test/server/lib/ExternalStorageAttachmentStore.ts
  test/server/lib/FilesystemAttachmentStore.ts
  test/server/lib/HostedStorageManager.ts
Labels: Attachments

#1422 FIX CI failing on install_chrome_for_tests
  buildtools/install_chrome_for_tests.sh
Labels: bug

#1420 Drop glyphicons and replace it by already existing icons in icons.css
  app/client/components/ColumnFilters.css
  app/client/components/DocConfigTab.js
  app/client/components/GristDoc.ts
  app/client/components/RecordLayoutEditor.js
  app/client/components/ValidationPanel.css
  app/client/components/ValidationPanel.js
  app/client/declarations.d.ts
  app/client/lib/koForm.css
  app/client/lib/koForm.js
  app/client/lib/multiselect.css
  app/client/lib/multiselect.js
  app/client/ui/Tools.ts
  app/client/widgets/AttachmentsWidget.ts
  app/common/UserConfig.ts
  test/nbrowser/Validations.ntest.js
Labels: gouv.fr, preview, -UX/UI

#1418 "view as" banner: add a tooltip so that users understand better what the screen does
  app/client/aclui/ACLUsers.ts
  app/client/components/Banner.ts
  app/client/components/ViewAsBanner.ts
  app/client/ui/GristTooltips.ts
  app/client/ui/tooltips.ts
  static/locales/en.client.json
  static/locales/fr.client.json
  test/nbrowser/AccessRules2.ts
Labels: gouv.fr, preview

#1428 Adding a shutdown method to the AttachmentsFileManager
  app/server/lib/ActiveDoc.ts
  app/server/lib/AttachmentFileManager.ts
  test/server/lib/AttachmentFileManager.ts
Labels: Attachments

#1458 Fixes error causing duplicate to fail on doc workers
  app/server/lib/uploads.ts
Labels: bug

#1475 fix: move tmp-promise from devDeps to Deps
  package.json
Labels: dependencies

#1478 feat: Explicitly pin python setuptools version
  Dockerfile
Labels: enhancement, dependencies
