Repository gristlabs/grist-core, pull requests merged in 2025-03, with the labels that each got.

#1479 Issue 1476 remove dev dependencies from docker images
  .dockerignore
  .github/workflows/docker_latest.yml
  .github/workflows/main.yml
  .github/workflows/translation_keys.yml
  Dockerfile
  README.md
  buildtools/build.sh
  documentation/develop.md
  package.json
  tsconfig-prod.json
Labels: enhancement, gouv.fr, self-hosting

#1423 Custom widgets: warn user it's risky
  app/client/lib/markdown.ts
  app/client/ui/CustomSectionConfig.ts
  app/client/ui/CustomWidgetGallery.ts
  app/client/ui/userTrustsCustomWidget.ts
  app/client/ui2018/alerts.ts
  app/client/ui2018/modals.ts
  static/img/security-alert-dark-theme.png
  static/img/security-alert.png
  static/locales/en.client.json
  static/locales/fr.client.json
  test/nbrowser/CustomWidgets.ts
  test/nbrowser/gristUtils.ts
Labels: gouv.fr, preview

#1497 chore: bump esbuild-loader from 4.2.2 to 4.3.0
  package.json
  yarn.lock
Labels: enhancement, dependencies, javascript

#1489 Minio : pass size argument
  app/server/lib/ExternalStorage.ts
  app/server/lib/MinIOExternalStorage.ts
  test/server/lib/AttachmentStoreProvider.ts
Labels: gouv.fr

#1387 Upgrade Dependency connect-redis from 3.4.0 to 6.1.3
  app/server/lib/gristSessions.ts
  package.json
  yarn.lock
Labels: dependencies, javascript, gouv.fr

#1376 feat: More readable Document settings
  app/client/ui/AdminPanel.ts
  app/client/ui/AdminPanelCss.ts
  app/client/ui/DocumentSettings.ts
Labels: gouv.fr, preview, -UX/UI
