Repository gristlabs/grist-core, pull requests merged in 2025-07, with the labels that each got.

#1655 Add support of Attachments
  app/client/components/FormRenderer.ts
  app/client/components/FormRendererCss.ts
  app/client/components/Forms/Field.ts
  app/client/components/Forms/FormView.ts
  app/client/components/Forms/Menu.ts
  app/client/components/Forms/styles.ts
  app/client/lib/formUtils.ts
  app/client/models/FormModel.ts
  app/client/models/entities/ColumnRec.ts
  app/client/ui/FormAPI.ts
  app/client/widgets/AttachmentsWidget.ts
  app/client/widgets/FieldBuilder.ts
  app/server/lib/DocApi.ts
  test/nbrowser/FormView1.ts
Labels: preview, -UX/UI, Attachments, forms

#1701 fix: override layoutSpec when changing widget to form
  app/client/components/Forms/FormView.ts
Labels: bug

#1706 Add new attachment rows quicker
  app/client/declarations.d.ts
  app/client/widgets/AttachmentsEditor.ts
  app/client/widgets/AttachmentsWidget.ts
Labels: preview

#1727 (themes) fix wrong theme set when using themeAppearance param
  app/client/ui2018/theme.ts
Labels: preview

#1719 Introduce extra truthy and falsy values at instance level
  README.md
  app/server/lib/NSandbox.ts
  sandbox/grist/usertypes.py
  test/server/lib/ActiveDoc.ts
Labels: enhancement, gouv.fr

#1721 User feedback on attachments/form long submission
  app/client/components/FormRenderer.ts
  app/client/components/FormRendererCss.ts
  app/client/declarations.d.ts
  app/client/lib/testState.ts
  app/client/lib/uploads.ts
  app/client/models/FormModel.ts
  app/client/widgets/AttachmentsEditor.ts
  app/client/widgets/AttachmentsWidget.ts
  app/common/TestState.ts
  static/locales/en.client.json
  test/nbrowser/AttachmentsWidget.ts
  test/nbrowser/FormView1.ts
  test/nbrowser/FormView2.ts
Labels: gouv.fr, preview
