Repository gristlabs/grist-core, pull requests merged in 2025-04, with the labels that each got.

#1340 Suggested implementation of themes refactoring
  app/client/app.css
  app/client/components/ChartView.ts
  app/client/components/WidgetFrame.ts
  app/client/lib/SafeBrowser.ts
  app/client/lib/getOrCreateStyleElement.ts
  app/client/models/AppModel.ts
  app/client/ui/PagePanels.ts
  app/client/ui/createPage.ts
  app/client/ui2018/cssVars.ts
  app/client/ui2018/theme.ts
  app/common/CssCustomProp.ts
  app/common/ThemePrefs-ti.ts
  app/common/ThemePrefs.ts
  app/common/Themes.ts
  app/common/gristUrls.ts
  app/common/themes/Base.ts
  app/common/themes/GristDark.ts
  app/common/themes/GristLight.ts
  app/plugin/grist-plugin-api.ts
  app/server/lib/ICreate.ts
  static/custom.css
  static/icons/icons.css
  test/client/ui2018/cssVars.ts
  test/common/ThemePrefs.ts
Labels: gouv.fr, preview

#1560 Improves behaviour for erroring archive downloads
  app/server/lib/Archive.ts
  app/server/lib/DocApi.ts
  test/server/lib/ActiveDoc.ts
  test/server/lib/Archive.ts
Labels: bug

#1536 Small improvements on forms accessibility
  app/client/components/FormRenderer.ts
  app/client/components/Forms/FormView.ts
  app/client/components/Forms/Section.ts
  app/client/components/Forms/elements.ts
  app/client/ui/FormContainer.ts
  app/client/ui/FormPage.ts
  app/client/ui/FormSuccessPage.ts
  static/locales/cs.client.json
  static/locales/de.client.json
  static/locales/en.client.json
  static/locales/es.client.json
  static/locales/eu.client.json
  static/locales/fr.client.json
  static/locales/pt_BR.client.json
  static/locales/ru.client.json
  static/locales/sk.client.json
  static/locales/zh_Hans.client.json
  test/nbrowser/FormView.ts
  test/nbrowser/gristUtils.ts
Labels: gouv.fr, Accessibility

#1566 Throw a more informative error if findAttachmentReferences query fails
  app/server/lib/DocStorage.ts
Labels: gouv.fr
