Repository gristlabs/grist-core, pull requests merged in 2025-05, with the labels that each got.

#1551 Adds download/upload attachment archive UIs
  app/client/lib/uploads.ts
  app/client/ui/DocumentSettings.ts
  app/client/ui/GristTooltips.ts
  app/client/ui/MakeCopyMenu.ts
  app/client/ui/ShareMenu.ts
  app/client/ui2018/modals.ts
  app/common/UserAPI.ts
  app/server/lib/ActiveDoc.ts
  app/server/lib/Archive.ts
  app/server/lib/DocApi.ts
  test/nbrowser/AttachmentsTransfer.ts
  test/server/lib/ActiveDoc.ts
Labels: preview, -UX/UI, Attachments

#1616 Add a light high contrast theme
  app/client/ui/RightPanel.ts
  app/client/ui/ThemeConfig.ts
  app/client/ui2018/theme.ts
  app/client/widgets/TextBox.css
  app/common/ThemePrefs.ts
  app/common/Themes.ts
  app/common/themes/Base.ts
  app/common/themes/HighContrastLight.ts
  test/nbrowser/CustomWidgets.ts
  test/nbrowser/Themes.ts
  test/nbrowser/gristUtils.ts
Labels: gouv.fr, preview, Accessibility

#1623 Enable themes when custom css is used
  README.md
  app/client/ui/AccountPage.ts
  app/client/ui/ThemeConfig.ts
  app/client/ui2018/theme.ts
  app/common/ThemePrefs.ts
  app/common/Themes.ts
  app/common/gristUrls.ts
  app/plugin/grist-plugin-api.ts
  static/custom.css
  stubs/app/server/server.ts
  test/nbrowser/Themes.ts
Labels: gouv.fr, Accessibility

#1634 Fix dark theme loading flash
  app/client/ui2018/theme.ts
  app/common/Themes.ts
Labels: gouv.fr, preview
