Repository gristlabs/grist-core, pull requests merged in 2025-01, with the labels that each got.

#1371 UPDATE node version in .nvmrc to be consistent with #1255
  .nvmrc
Labels: anct

#1320 Adds initial support for external attachments using the Filesystem or MinIO
  app/common/DocumentSettings.ts
  app/server/generateInitialDocSql.ts
  app/server/lib/ActiveDoc.ts
  app/server/lib/AttachmentFileManager.ts
  app/server/lib/AttachmentStore.ts
  app/server/lib/AttachmentStoreProvider.ts
  app/server/lib/DocApi.ts
  app/server/lib/DocManager.ts
  app/server/lib/DocStorage.ts
  app/server/lib/ExternalStorage.ts
  app/server/lib/FlexServer.ts
  app/server/lib/ICreate.ts
  app/server/lib/MinIOExternalStorage.ts
  app/server/lib/checksumFile.ts
  app/server/lib/coreCreator.ts
  app/server/utils/MemoryWritableStream.ts
  app/server/utils/gristify.ts
  test/fixtures/docs/BlobMigrationV9.grist
  test/fixtures/docs/DefaultValuesV9.grist
  test/fixtures/docs/Hello.grist
  test/server/docTools.ts
  test/server/lib/ActiveDoc.ts
  test/server/lib/AttachmentFileManager.ts
  test/server/lib/AttachmentStoreProvider.ts
  test/server/lib/DocStorage.js
  test/server/lib/DocStorageMigrations.ts
  test/server/lib/FilesystemAttachmentStore.ts
  test/server/lib/HostedStorageManager.ts
  test/upgradeDocumentImpl.ts
Labels: Attachments

#1368 Dependencies update
  package.json
  yarn.lock
Labels: enhancement, javascript, gouv.fr

#1381 Bump @gristlabs/express-session from 1.17.0 to 1.18.1-grist1
  package.json
  yarn.lock
Labels: dependencies, javascript, gouv.fr

#1247 Issue 1242 url preview
  README.md
  app/common/gristUrls.ts
  app/server/lib/sendAppPage.ts
  static/locales/en.server.json
  test/nbrowser/HomeIntro.ts
  test/nbrowser/NewDocument.ntest.js
Labels: preview

#1390 chore: Fix webpack version import warning
  stubs/app/common/version.ts
Labels: enhancement, gouv.fr

#1388 Update dependencies engine.io & engine.io-client
  app/server/lib/GristSocketServer.ts
  package.json
  yarn.lock
Labels: dependencies, javascript, gouv.fr

#1389 Dependency Upgrade bump Express from 4.20.0 to 4.21.2
  app/server/lib/FlexServer.ts
  package.json
  yarn.lock
Labels: dependencies, javascript, gouv.fr

#1394 Upgrade Depencency esbuild-loader from 2.19.0 to 4.2.2
  buildtools/webpack.api.config.js
  buildtools/webpack.check.js
  buildtools/webpack.config.js
  package.json
  yarn.lock
Labels: dependencies, javascript, gouv.fr
